const restaurants = [
  'archive-bar-and-kitchen-san-francisco',
  'the-lavender-fox',
  'the-harborview-flower',
  'the-jungle-salmon',
  'the-electric-fish',
  'the-island-victory',
  'vista',
  'lavender',
  'the-gallery',
  'gastrognome',
  'acapella',
  'the-nifty-factory',
  'the-sailing-exchange',
  'the-copper-commander',
  'the-underwater-room',
  'the-harborview-lane',
  'paramount',
  'fluorescence',
  'intermezzo',
  'blueprint',
  'podium',
  'the-glass-bay',
  'the-coriander-garden',
  'the-island-shrimp',
  'the-juniper-lane',
  'the-cocoa-monument',
  'the-grand-fish',
  'the-japanese-after-dark',
  'maximus',
  'bambino',
  'candle',
  'the-sugar-boulevard',
  'the-harmonic-beehive',
  'the-coriander-wharf',
  'the-southern-afternoon',
  'the-kings-boar',
  'bounty',
  'twilight',
  'the-chili-angel',
  'modesty',
  'pavilion',
  'the-jade-boulevard',
  'the-amber-saloon',
  'the-malt-beehive',
  'the-autumn-dragon',
  'the-queens-orchid',
  'clarity',
  'the-noodle-cottage',
  'bones',
  'lily',
  'the-crown',
  'the-pepper-grill',
  'the-electric-diner',
  'the-jungle-block',
  'the-corner-view',
  'the-proud-elephant',
  'roots',
  'streetwise',
  'the-spring-lighthouse',
  'the-emperor',
  'the-peacock',
  'the-incredible-exhibit',
  'the-pearl-moments',
  'the-magical-brothers',
  'the-shining-night',
  'the-first-willow',
  'the-depot',
  'indigo',
  'retro',
  'prospects',
  'meadows',
  'the-summer-scarf',
  'the-paradise-oriental',
  'the-island-goddess',
  'the-bright-pizzeria',
  'the-square-beehive',
  'chance',
  'ivy',
  'whisperwind',
  'glasshouse',
  'after-dark',
  'the-cocoa-goat',
  'the-incredible-horse',
  'the-harlequin-knight',
  'the-court-walk',
  'the-chili-lane',
  'serenity',
  'shambles',
  'charm',
  'phish-shack',
  'rogue',
  'the-coriander-maple',
  'the-bamboo-lane',
  'the-square-door',
  'the-delhi-orchard',
  'the-cocoa-junction',
  'solitude',
  'catch',
  'happening',
  'chapter',
];

module.exports = restaurants;

// let temp = {};
// let names = [
//   'the-japanese-after-dark',
//   'the-chili-angel',
//   'the-noodle-cottage',
//   'the-spring-lighthouse',
//   'prospects',
//   'charm',
//   'lavender',
//   'twilight',
// ];
// let i = 0;
// restaurants.forEach((val, index) => {

//   if (temp[val]) {
//     temp[val]++;
//     console.log(val, temp[val]);
//     // restaurants[index] = names[i];
//     // i++;
//   } else {
//     temp[val] = 1;
//   }
// });

// console.log(restaurants);
